services:
  web:
    container_name: "vessel-web"
    build:
      dockerfile: ./apps/frontend/Dockerfile
      args:
      - BACKEND_URL=/api
    ports:
    - "80:80"
    stdin_open: true
    tty: true