name: Deploy to App Service
on:
  release:
      types:
        - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}-backend:${{ github.sha }}
          file: apps/backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: app-cswf-vess-api-westeu-prd
          publish-profile: ${{ secrets.AZURE_WEBAPP_API_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}-backend:${{ github.sha }}'